---
- hosts: localhost
  gather_facts: False
  tasks:
    - debug:
        msg: "{{ zuul_s3.access_key }}"
    - debug:
        msg: "{{ zuul_s3.access_key | trim }}"
    - debug:
        msg: "{{ zuul_s3.secret_key }}"
    - debug:
        msg: "{{ zuul_s3.secret_key | trim }}"
    - include_role:
        name: generate-zuul-manifest
    - include_role:
        name: upload-logs-s3
      vars:
        zuul_log_bucket: "zuul-stackhpc"
        zuul_log_aws_access_key: "{{ zuul_s3.access_key | trim }}"
        zuul_log_aws_secret_key: "{{ zuul_s3.secret_key | trim }}"
        upload_logs_s3_endpoint: "https://api.sms-lab.cloud:6780"
