---
- hosts: localhost
  gather_facts: False
  tasks:
    - include_role:
        name: generate-zuul-manifest
    - include_role:
        name: upload-logs-s3
      vars:
        zuul_log_bucket: "{{ zuul_s3.bucket }}"
        zuul_log_aws_access_key: "{{ zuul_s3.access_key }}"
        zuul_log_aws_secret_key: "{{ zuul_s3.secret_key }}"
        upload_logs_s3_endpoint: "{{ zuul_s3.endpoint }}"
