---
- name: Create job header and inventory
  hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_path_shard_build: true
    - log-inventory

- name: Setup Zuul environment
  hosts: all
  pre_tasks:
    - name: Gather network facts
      setup:
        gather_subset: 'network'

  roles:
    - add-build-sshkey
    - start-zuul-console
    - ensure-output-dirs

- name: Prepare workspace and configure mirrors
  hosts: all
  roles:
    - validate-host
    - prepare-workspace-git

- name: Checkout stackhpc branch for downstream forks
  vars:
    stackhpc_forked_projects:
      - openstack/requirements
  shell: |
    cd {{ item.src_dir }}
    git checkout {{ zuul.branch | regex_replace('^stable/(.+)$', 'stackhpc/\1') }} \
      || true
  loop: "{{ zuul.projects.values() | list }}"
  when: item.name in stackhpc_forked_projects
