- name: Checkout correct branch for all projects
  shell: |
    cd ./{{ item.src_dir }}
    echo "Current: $(git log --oneline -1)"
    git checkout {{ zuul.branch }} \
      || git checkout {{ zuul.branch | regex_replace('^stackhpc/(.+)$', 'stable/\1') }} \
      || true
    echo "Final: $(git log --oneline -1)"
  loop: "{{ zuul.projects.values() | list }}"
  when: item.checkout_description == 'project default branch'
