---
- name: Ensure Zuul is configured
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Ensure Zuul namespace
      kubernetes.core.k8s:
        name: zuul
        api_version: v1
        kind: Namespace
        state: present

    - name: Ensure CRDs
      kubernetes.core.k8s:
        definition: "{{ zuul_operator_crd }}"
        namespace: "zuul"
        state: present

    - name: Ensure RBAC
      kubernetes.core.k8s:
        namespace: "zuul"
        definition: "{{ zuul_operator_rbac }}"
        state: present

    - name: Ensure Operator
      kubernetes.core.k8s:
        definition: "{{ zuul_operator_operator }}"
        namespace: "zuul"
        state: present

    - name: Ensure Secrets
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          type: "{{ item.type | default('Opaque') }}"
          metadata:
            name: "{{ item.name }}"
            namespace: "{{ item.namespace | default('zuul') }}"
          data: "{{ item.data }}"
        state: present
      loop: "{{ zuul_operator_secrets }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Ensure additional config
      kubernetes.core.k8s:
        namespace: "zuul"
        state: present
      loop: "{{ zuul_operator_additional }}"

    - name: Ensure Zuul CR
      kubernetes.core.k8s:
        definition: "{{ zuul_operator_cr }}"
        namespace: "zuul"
        state: present

    - name: Download Contour CRDs
      ansible.builtin.get_url:
        url: https://projectcontour.io/quickstart/contour.yaml
        dest: /tmp/ansible_zuul_contour.yaml
        mode: '0664'
      check_mode: false

    - name: Ensure Contour namespace
      kubernetes.core.k8s:
        name: projectcontour
        api_version: v1
        kind: Namespace
        state: present

    - name: Ensure Contour CRDs
      kubernetes.core.k8s:
        src: /tmp/ansible_zuul_contour.yaml
        state: present

    - name: Ensure Gateway API CRDs
      kubernetes.core.k8s:
        namespace: "zuul"
        src: "{{ zuul_operator_gateway_api_crd_url }}"
        state: present
      when: zuul_operator_gateway_api_crd_url | length > 0
      tags: gateway-api

    - name: Ensure Gateway API Gateways
      kubernetes.core.k8s:
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: Gateway
          metadata:
            name: "{{ item.name }}"
          spec: "{{ item.spec }}"
        namespace: "zuul"
        state: present
      loop: "{{ zuul_operator_gateway_api_gateways }}"
      loop_control:
        label: "{{ item.name }}"
      tags: gateway-api

    - name: Ensure Gateway API HTTPRoutes
      kubernetes.core.k8s:
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: "{{ item.name }}"
          spec: "{{ item.spec }}"
        namespace: "zuul"
        state: present
      loop: "{{ zuul_operator_gateway_api_httproutes }}"
      loop_control:
        label: "{{ item.name }}"
      tags: gateway-api
