---
name: On Pull Request

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy-zuul:

    runs-on: self-hosted

    env:
      ANSIBLE_FORCE_COLOR: True
      ANSIBLE_VAULT_PASSWORD_FILE: .vault.txt

    steps:
    - uses: actions/checkout@v4

    - name: Set Ansible Vault password file
      run: |
        echo ${{ secrets.ANSIBLE_VAULT_PASSWORD }} > $ANSIBLE_VAULT_PASSWORD_FILE

    - name: Install dependencies
      run: >
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Generate kubeconfig
      env:
        KUBE: ${{secrets.KUBE}}
        OS_CLOUD: "smslab-stackhpc-ci"
      run: |
        mkdir -p ~/.kube
        echo "$KUBE" > ~/.kube/config

    - name: Run playbook
      run: >
        ansible-playbook -i ansible/inventory ansible/run.yml --check --diff -vvv

    - name: Remove credentials
      run: |
        rm -f ~/.kube/config .vault.txt

